### ISSUE TITLE
Hyphen in test name (``...-...``) crashes VS Code

### ISSUE THREAD

**Issue by bytesource** [ijrussell/essential-fsharp#2]
Hi Ian, 

On page 56 you warn against using special characters between double backticks

> WARNING: If you use the double backtick naming style, do not use any odd chars like
> [,|-;.]. These used in test names causes the ionide extension to crash. [Correct: 2022-05-20]

However, later you use hyphens in test names which crash VS Code, at least for me:

**Page 75**:
``` fsharp
[<Fact>]
let ``when product exists in non-empty order`` () =
// [...]
```

**Page 77**:
``` fsharp
[<Fact>]
let ``should do nothing for non-existant productid`` () =
// [...]
```
I'm currently on page 77, so there might appear more test names with a hyphen later in the book. 

Removing each hyphen resolves the issue, which is great!

**Comment by ijrussell** [comment]
Thanks
