### ISSUE TITLE
A Few Typos

### ISSUE THREAD

**Issue by bytesource** [ijrussell/essential-fsharp#5]
Hi Ian, 

I tremendously enjoyed your book! Your style of returning to previous code examples and improving them based on newly learned knowledge helped me connect the dots. 

Only in the last chapter, I would have loved to see how to "wire up" the API with the HTML. But I'm sure I can figure it out myself :-)

I found a few typos that I corrected in this commit:

https://github.com/bytesource/essential-fsharp/commit/d7f80dd4f8fc55fc0776992be92f9b8e1e2a5f32

Provided all changes are indeed correct, I can send a pull request if you like.

Keep up the good work!

**Comment by ijrussell** [comment]
Hi Stefan,

Thanks for the comments. I wanted to do the minimum possible for the last three chapters to force you to dive into the giraffe documentation.

I've commented on a couple of things. Create a PR and I will merge them in. 

Regards,
Ian

**Comment by bytesource** [comment]
Hi Ian, 
Thanks for spotting the `Spend.create` typos. This what happens when there's no compiler to yell at me :-)

I corrected the mistakes and submitted a PR.

Regards,

Stefan
