### ISSUE TITLE
Error in Chapter 8

### ISSUE THREAD

**Issue by emaphis** [ijrussell/essential-fsharp#7]
In Chapter 8 - Functional Validation
In the "Where are we now " section
You forgot the 

let (|IsValidDate|_|) (input:string) =
    let (success, value) = input |> DateTime.TryParse 
    if success then Some value else None

Active pattern.

It should probably follow the "IsBoolean" pattern.

**Comment by ijrussell** [comment]
Oops! Thanks for reporting the issue. I hope that you're enjoying what you've read so far?
